### ISSUE TITLE
Subscription preference

### ISSUE THREAD

**Issue by kdamball** [nichekie/nichekie#2]
- Allow subscription to certain products only.

**Comment by kdamball** [comment]
@Dennisirafay This is assigned to you

**Comment by kdamball** [comment]
•	Product/Company Category of whose offers a subscriber wishes to subscribe to. The option should provide multiple selection option.
•	Unsubscribe option

**Comment by Dennisirafay** [comment]
![products categories](https://cloud.githubusercontent.com/assets/11574904/7085676/ae5d7028-df81-11e4-9c2f-041b8b7e2cba.JPG)

I find this list of categories great. We can use it.

**Comment by kdamball** [comment]
## THIS DOES NOT HELP! 

I need categories according to the research you have done based companies you will be contacting!

**Comment by Dennisirafay** [comment]
Well. See the list (in your email) as per researched stores in which we will start with. Please let us meet either today or tomorrow to finalize things before you start your new contract.

**Comment by kdamball** [comment]
On it, cheers for the update!
