### ISSUE TITLE
Homepage Redesign

### ISSUE THREAD

**Issue by kdamball** [nichekie/nichekie#8]
- Include `about` page details in the homepage.
- Send a .psd or image file with design specs and content

**Comment by kdamball** [comment]
I added a sample about section on the homepage. It will need a new image/font-icon.

**Comment by Dennisirafay** [comment]
Hey, kindly suggest on the size of the design for the homepage. Sadly I have to do a redesign as my computer is simply dead. Do that please. Am doing the redesigning work now.

**Comment by kdamball** [comment]
![homepage](https://cloud.githubusercontent.com/assets/3318312/7001887/7f86ea3e-dc4a-11e4-84e6-4fb628fcdd4e.png)

This is the current homepage

**Comment by kdamball** [comment]
![homepage](https://cloud.githubusercontent.com/assets/3318312/7026572/38bbf734-dd53-11e4-927d-e4fe933861e8.png)

Updated homepage

**Comment by Dennisirafay** [comment]
I love the redesigning work. I was a bit struggling with redesigning of the logo as you suggested as I didnt have Photoshop. Got it now. I am redoing it.

On your redesigned homepage, that word nichekie, I think the font is too NORMAL, I suggest you change it.

**Comment by kdamball** [comment]
![contact](https://cloud.githubusercontent.com/assets/3318312/7221397/0a60766e-e6f2-11e4-9c3d-aad447f1c993.png)

Contact section similar to the image above but going at the page footer (bottom of the page)

**Comment by Dennisirafay** [comment]
I have tried to subscribe and proved you have resolved the confirmation issue. I tried to use same details and got the message "This number is already in our records." I tried to change the number only (leaving my first name and last name and email the same) and I was subscribed successfully. 

Does this make the number the only unique information from every subscriber?

**Comment by kdamball** [comment]
Yes, we want to avoid having multiple subscriptions for phone numbers. The idea is that when we send out notifications, we avoid spamming the same phone number several times with similar information (also, avoiding extra SMS costs).
